### ISSUE TITLE
Bug: Bottom row of dots out of bounds in some screen dimensions

### ISSUE THREAD

**Issue by danieldesira** [danieldesira/DanielsConnect4#30]
To investigate further by asking user for screen dimensions so we can reproduce it on the dev environment.

**Comment by danielmartza93** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/129845277/235946341-d2ea7f2b-9ff2-47de-af70-0e3bc1dcfe57.png)

**Comment by danieldesira** [comment]
Resolved.
